### ISSUE TITLE
Example in the README.md

### ISSUE THREAD

**Issue by BrenoAV** [italojs/resize_dataset_pascalvoc#15]
Hi, @italojs.

On the [README.md](https://github.com/italojs/resize_dataset_pascalvoc/blob/master/README.MD) there's confusion with the example. Check the [resized image](https://github.com/italojs/resize_dataset_pascalvoc/blob/master/images_example/IMG_20181109_165212_new.jpg), it's 150x150 and **not 200x200**.

For 150x150:
- ScaleX = 150/650 = 3/13
- ScaleY = 150/590 = 15/59

Original [BBOX ORIGINAL](https://github.com/italojs/resize_dataset_pascalvoc/blob/6f157771f008ed3fc8ebb75fa73e305228dba518/README.MD?plain=1#L148-L151):

$x_{min} = 74$
$y_{min} = 192$
$x_{max} = 267$
$y_{max} = 499$

Scaling:

$x_{min} = 74 \times 3/13 = 17.08$
$y_{min} = 192 \times 15/59 = 48.81$
$x_{max} = 267 \times 3/13 = 61.62$
$y_{max} = 499 \times 15/59 = 126.86$

As you can see in [your example](https://github.com/italojs/resize_dataset_pascalvoc/blob/6f157771f008ed3fc8ebb75fa73e305228dba518/README.MD?plain=1#L206-L209), the values matched.

**Comment by italojs** [comment]
hi @BrenoAV could you send a PR fixing it?

**Comment by BrenoAV** [comment]
I've created. I also added the calculus part, feel free to remove it if you want. 

#16
