### ISSUE TITLE
Is the aspect ratio preserved?

### ISSUE THREAD

**Issue by monocongo** [italojs/resize_dataset_pascalvoc#4]
I am interested in using this code to resize a dataset into dimensions where both width and height are multiples of 16. For example 320x480 or 400x160 (both width and height are evenly divisible by 16). Is it possible to do this using this package? Will the aspect ratio of the images be preserved, and if so how is padding/border handled?

Thanks in advance for your response and any suggestions or comments.

**Comment by monocongo** [comment]
From what I can see in the `image.resize` function it appears that the aspect ratio of the image is not preserved and the image is scaled based on whatever new image dimensions are specified. Or have I misunderstood what the code does?

**Comment by italojs** [comment]
Sorry by late.
Sorry, this repository dont have this feature, but you can implement it, what do you think about?
here have some implementations that can help you https://stackoverflow.com/questions/44650888/resize-an-image-without-distortion-opencv

**Comment by monocongo** [comment]
In case it is helpful I now have resizing code that preserves aspect ratio and pads on the right and bottom of the resized image: https://github.com/monocongo/cvdata/blob/master/cvdata/resize.py

The above code works for PASCAL VOC and KITTI annotations.

**Comment by hlmhlr** [comment]
> In case it is helpful I now have resizing code that preserves aspect ratio and pads on the right and bottom of the resized image: https://github.com/monocongo/cvdata/blob/master/cvdata/resize.py
> 
> The above code works for PASCAL VOC and KITTI annotations.

Dear all,  I need to resize the image while maintaing the aspect ratio and so the bounding boxes with respect to the input images same as in original one. So, could you pleas ehlp me out. Since the above mentioned link is broken.  thanks in advance.
