### ISSUE TITLE
Image.py resize function contains bug.

### ISSUE THREAD

**Issue by TechMi97** [italojs/resize_dataset_pascalvoc#6]
I resized images and annotations using the code, but seems like there is a problem with the code.
The bounding box goes out of the box or sometimes the bounding box looks flipped horizontally.

something is wrong here:

     **scale_x = newSize[0] / image.shape[1]
     scale_y = newSize[1] / image.shape[0]**

    image = cv2.resize(image, (newSize[0], newSize[1]))

    newBoxes = []
    xmlRoot = ET.parse(xml_path).getroot()
    xmlRoot.find('filename').text = image_path.split('/')[-1]
    size_node = xmlRoot.find('size')
    size_node.find('width').text = str(newSize[0])
    size_node.find('height').text = str(newSize[1])

    for member in xmlRoot.findall('object'):
        bndbox = member.find('bndbox')

        xmin = bndbox.find('xmin')
        ymin = bndbox.find('ymin')
        xmax = bndbox.find('xmax')
        ymax = bndbox.find('ymax')
        
        xmin.text = str(np.round(int(float(xmin.text)) * scale_x))
        ymin.text = str(np.round(int(float(ymin.text)) * scale_y))
        xmax.text = str(np.round(int(float(xmax.text)) * scale_x))
        ymax.text = str(np.round(int(float(ymax.text)) * scale_y))

        newBoxes.append([
            1,
            0,
            int(float(xmin.text)),
            int(float(ymin.text)),
            int(float(xmax.text)),
            int(float(ymax.text))
            ])

   

![boxed_10018_00004277](https://user-images.githubusercontent.com/44256294/81474745-0651bd00-923a-11ea-999a-f5aed436d500.jpg)

**Comment by italojs** [comment]
can you provide us a data sample with some images that got this bug? I will try to reproduce the problem and fix this bug @TechMi97

**Comment by TechMi97** [comment]
Hi, It was actually mistake with the dataset. Some of the images are horizontal orientation (width>hieght). While some had (height>width). So I had to add cv2.transpose(image) and also 
exchanged the coords. 
img=cv2.transpose(image)

       holdxmin=xmin.text
        holdxmax=xmax.text
        xmin.text=ymin.text
        ymin.text=holdxmin
        xmax.text=ymax.text
        ymax.text=holdxmax
